asr:
  channels: 1
  model_path_cn: asr_service/CN_model/offline_encoder.om
  model_path_en: asr_service/EN_model/offline_encoder.om
  model_type: EN
  sample_rate: 44100
  vocab_path_cn: asr_service/CN_model/vocab.txt
  vocab_path_en: asr_service/EN_model/vocab.txt
llm:
  api:
    api_key: sk-262419ac92684077aca08779a67e68a4
    api_url: https://api.deepseek.com/v1/chat/completions
    max_tokens: 512
    model: deepseek-chat
    provider: deepseek
    stream: true
    system_prompt: 你是一个智能语音助手，扮演的是爱莉希雅，你的输入是由语音识别转换而来，会有很多错误以及无关的内容，需要你自动修正，另外，你的输出会语音合成，所以不要加括号
    temperature: 1.0
    top_p: 0.9
  local:
    max_tokens: 128
    model_name: qwen
    qwen_model_path: /home/HwHiAiUser/.mindnlp/model/Qwen/Qwen1.5-0.5B-Chat
    system_prompt: You are a helpful and friendly chatbot
    temperature: 1.0
    tinyllama_model_path: /home/HwHiAiUser/.mindnlp/model/TinyLlama/TinyLlama-1.1B-Chat-v1.0
  mode: api
logging:
  backup_count: 5
  file: ai_assistant.log
  level: INFO
  max_bytes: 10485760
services:
  asr: 5001
  llm: 5002
  orchestrator: 5000
  tts: 5003
  voice_chat: 5004
  web_ui: 8080
  yolo: 5005
streaming:
  max_wait_time: 3.0
  min_chunk_length: 10
  sentence_delimiters:
  - 。
  - '!'
  - '?'
  - '!'
  - '?'
  - '

    '
  - .
  - ;
tts:
  api:
    api_key: sk-3daa6c3cbffa4aeebce31a49f75a2c7b
    format: PCM_22050HZ_MONO_16BIT
    model: cosyvoice-v3
    provider: cosyvoice
    sample_rate: 22050
    voice: cosyvoice-v3-elysia-bd5b817e991d44b88724c728f08a54b1
  local:
    model_path: tts_service/models/cosyvoice
  mode: api
  voice_enrollment:
    default_model: cosyvoice-v2
    default_prefix: myvoice
    max_poll_attempts: 30
    poll_interval: 10
voice_chat:
  continue_dialogue_timeout: 10.0
  enable: true
  input_device: 1
  interrupt_mode: true
  interrupt_reply: 好吧好吧，我不说了还不行吗~
  interrupt_words:
  - 停止
  - 暂停
  - 别说了
  - 闭嘴
  - 停下
  min_audio_length: 0.7
  output_device: null
  output_volume: 50
  silence_duration: 0.5
  silence_threshold: 200
  thinking_reply: 好，我知道了，等我想一下
  wake_mode: true
  wake_reply: 哎呦，谁在叫我呀？
  wake_words:
  - 助手
  - 你好
  - 嘿
  - 小
  - 小爱
web:
  enable: true
  share: true
  title: AI语音助手配置中心
yolo:
  camera_index: null
  confidence_threshold: 0.5
  enable_streaming: true
  labels_file: yolo_service/YOLOV5USBCamera/python/src/label.py
  max_fps: 15
  model_height: 640
  model_path: yolo_service/models/yolov5s.om
  model_width: 640
  nms_threshold: 0.4
